### ISSUE TITLE
Snake: reset output to zero when input is unplugged

### ISSUE THREAD

**Issue by phdsg** [gbrandt1/southpole-vcvrack#8] opened 2018-02-09 20:14 UTC
just noticed that when unplugging a cable from the input the output holds the last sample value.
probably easy to fix.

anyway, great module idea.
also love your other modules. 
awesome work.

**Comment by gbrandt1** [comment] 2018-02-09 20:25
thanks, yes i never considered unplugging ;-) will be fixed

**Comment by gbrandt1** [comment] 2018-02-22 18:25
new version with 0-F buss selection in master if you would like to test

**Comment by phdsg** [comment] 2018-02-22 19:11
something's wrong with the Aux.cpp. trying to build master i get this error:
```
g++ -DTEST -I./eurorack -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DSLUG=Southpole -DVERSION=0.5.3 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -Wsuggest-override -std=c++11 -c -o build/src/Aux.cpp.o src/Aux.cpp
g++.exe: fatal error: input file 'build/src/Aux.cpp.o' is the same as output file
compilation terminated.
make: *** [../../compile.mk:54: build/src/Aux.cpp.o] Error 1

```
must be something wrong with the name of that file as i managed to get a successful build renaming Aux.cpp to Auxes.cpp and changing that in the Makefile too.

**Comment by phdsg** [comment] 2018-02-22 19:17
other than that. nice update.

**Comment by gbrandt1** [comment] 2018-02-22 19:39
did you do make clean? why is it trying to read the object file ... weird. what's your platform?
also, the update is not done, still working on it

**Comment by phdsg** [comment] 2018-02-22 19:44
i'm using win7 (mingw64). all cleaned before every make.
yeah it's super weird. because when i revert the changes i'll get the same error.
i'll try on another machine.

**Comment by gbrandt1** [comment] 2018-02-22 19:48
will try on my win10 laptop on the weekend. a bizzare error, i didn't check the object file in as can be seen easily in the file browser, and the Makefile only asks explicitly for Aux.cpp, no wildcards in the game at all...

**Comment by phdsg** [comment] 2018-02-22 19:52
what's even weirder... the plugin didn't load the Aux.svg either. had to rename that too...

**Comment by gbrandt1** [comment] 2018-02-22 19:58
wtf ... maybe some problem with the somewhat generic name ... expecting "aux" files or something??

**Comment by phdsg** [comment] 2018-02-22 20:04
well, it's all fine on my linux box.
so i'm gonna check what's wrong with my windows machine.
closing this. opening a new one if i can't find the problem.

**Comment by gbrandt1** [comment] 2018-02-22 20:05
thanks for testing. 
lmk if you find a problem with the new snake logic.

**Comment by phdsg** [comment] 2018-02-23 10:35
ok, last reply to this issue. i'll let you check for yourself before i open a new issue.
tried a few more things yesterday:
updated all of the msys, fresh rack and plugin clones, etc.
basically everything to rule out any error with the build environment.
and today i also got another report of the same error...

**Comment by phdsg** [comment] 2018-02-23 10:36
aaaand, look at this: http://kizu514.com/blog/forbidden-file-names-on-windows-10/

**Comment by phdsg** [comment] 2018-02-23 15:32
didn't test the snake much...sry.
because maan, that riemann is awesome. sucked me in for over an hour...

**Closed as completed** 2018-02-23 20:42 UTC

**Comment by gbrandt1** [comment] 2018-02-23 21:10
wow! looks like i hit the jackpot... ok i just reproduced the issue on my Win10 laptop, renamed to Aux_ and can compile now

**Comment by phdsg** [comment] 2018-02-23 21:12
yes all good now :) weirdest issue ever.
any plans on doing the other parasites too?
also  thx again for that riemann+sns.

**Comment by gbrandt1** [comment] 2018-02-23 21:16
yes i'm considering it. 
i mean Warps/ Tapeworm is already dark and compact so that would be kind of moot.
but nobody did the Frames parasite so far. will check with the other developers in order not to duplicate stuff. would also be cool to complete the MI collection in particular Peaks and Streams
